[Basics]
pretrained_model_name_or_path = ""
train_data_dir = ""
resolution = "512"
seed = 23
max_train_steps = 10000
max_train_epochs = 50
clip_skip = 1

[Save]
output_dir = ""
output_name = "exp-1002-sd15-lora32a16-a"
save_precision = "fp16"
save_model_as = "safetensors"
save_every_n_epochs = 5
save_state = false
save_last_n_steps_state = 10

[Logging]
logging_dir = "logs_training"
log_with = "tensorboard"
log_prefix = "exp-1002-sd15-lora32a16-a_"

[Network_setup]
network_dim = 32
network_alpha = 16
dim_from_weights = false
network_dropout = 0
network_train_unet_only = false
network_train_text_encoder_only = false
resume = false

[LyCORIS]
network_module = "lycoris.kohya"
network_args = [ "conv_dim=0", "algo=lora", "preset=attn-mlp",]

[Optimizer]
train_batch_size = 8
gradient_checkpointing = false
gradient_accumulation_steps = 1
optimizer_type = "AdamW8bit"
unet_lr = 0.0005
text_encoder_lr = 0.0005
max_grad_norm = 1
optimizer_args = [ "weight_decay=0.1", "betas=0.9,0.99",]

[Lr_scheduler]
lr_scheduler_type = ""
lr_scheduler = "constant_with_warmup"
lr_warmup_steps = 3500
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1.0

[Captions]
shuffle_caption = false
caption_extension = ".txt"
keep_tokens = 0
caption_dropout_rate = 0.05
caption_dropout_every_n_epochs = 0
caption_tag_dropout_rate = 0.0
max_token_length = 150
weighted_captions = false
token_warmup_min = 1
token_warmup_step = 0

[Training_preciscion]
mixed_precision = "bf16"
full_fp16 = false

[ARB]
enable_bucket = true
min_bucket_reso = 320
max_bucket_reso = 960
bucket_reso_steps = 64
bucket_no_upscale = false

[Attention]
mem_eff_attn = false
xformers = true

[Data_augmentation]
color_aug = false
flip_aug = false
random_crop = false

[Cache_latents]
cache_latents = true
vae_batch_size = 1
cache_latents_to_disk = true

[Sampling_during_training]
sample_sampler = "ddim"

[Dataset]
max_data_loader_n_workers = 8
persistent_data_loader_workers = true
dataset_repeats = 1

[Regularization]
prior_loss_weight = 1.0

[SDv2]
v2 = false
v_parameterization = false
scale_v_pred_loss_like_noise_pred = false

[Huggingface]
save_state_to_huggingface = false
resume_from_huggingface = false
async_upload = false

[Debugging]
debug_dataset = false

[Deprecated]
use_8bit_adam = false
use_lion_optimizer = false
learning_rate = 0.0002

[Others]
lowram = false
training_comment = ""
